### ISSUE TITLE
Add setting for "create branch based on story name" base path

### ISSUE THREAD

**Issue by woelmer** [Daniel-Griffiths/vscode-clubhouse#219]
The default in clubhouse is to create a branch name with /feature/ch####/story name. The default with this extension is /myname/ch####/story name. Either change the default to match clubhouse or allow me to change what the base path is for a new branch in vscode settings.

Thanks for making this extension.

**Comment by Daniel-Griffiths** [comment]
Sorry @woelmer, just seen this issue! I will get around to adding this in when I get a chance, same with your other issue. :slightly_smiling_face: 

Thanks for the feedback.

**Comment by Daniel-Griffiths** [comment]
Hey @woelmer I have deployed a new version, it now has the option to customise the branch format 

![image](https://user-images.githubusercontent.com/1458314/99596636-909b8a80-29ee-11eb-9cf9-29f52f6cca65.png)

See the readme to view which params are available.
