### ISSUE TITLE
Create pull request resulted in 500 page on GitHub

### ISSUE THREAD

**Issue by woelmer** [Daniel-Griffiths/vscode-clubhouse#220]
The url it went to resulted in a 500 on GitHub.

https://github.com/companyname/myproject/compare/feature/ch3312/fix-imports?expand=1&title=Fix%20imports&body=Story%20details:%20https://app.clubhouse.io/story/3312

**Comment by Daniel-Griffiths** [comment]
Hey @woelmer 

Just to check, did you push a commit to the repo first using the following option?

![image](https://user-images.githubusercontent.com/1458314/99596809-d48e8f80-29ee-11eb-8ccd-0b9dd9b37073.png)

Creating a PR wont work unless any commits have been made. Ideally I should add something to the UI to inform the user.
