### ISSUE TITLE
Why not use the clubhouse SDK?

### ISSUE THREAD

**Issue by kevinsperrine** [Daniel-Griffiths/vscode-clubhouse#28]
Just wondering if there was a specific reason not to? If so, do you have plans to bump to v3 of the API? Can I help with any issues or features?

https://github.com/clubhouse/clubhouse-lib

**Comment by Daniel-Griffiths** [comment]
Sorry @kevinsperrine I only just noticed this issue!

I was not aware that lib existed, I will look at implementing it. I will keep this PR open in the meantime until that has happened 😄 

**EDIT:** Mostly got this working with the lib, need's a bit of cleanup and then this should be good to merge. Thank's again for the suggestion!

**Comment by Daniel-Griffiths** [comment]
In regards to the second question is there anything you specifically would like to see added to this project? 

I mainly made this extension to match my own workflow, but am happy to change/add things if it help's other developers!

**Comment by Daniel-Griffiths** [comment]
Finally got a chance to add this in over the xmas break! 😄 

I will mark this issue as completed.
