### ISSUE TITLE
Update branch naming logic

### ISSUE THREAD

**Issue by marlon-baskin** [Daniel-Griffiths/vscode-clubhouse#337]
Clubhouse.io has changed its name to Shortcut.io since the last time this extension was updated, and as such they've changed their naming convention for story-based branch names. Given story number `XXXX`, branch names now use `sc-XXXX` instead of `chXXXX`.

**Comment by marlon-baskin** [comment]
I have submitted a pull request for this small update.

**Comment by Daniel-Griffiths** [comment]
Thanks for the PR 🙏🏻
