### ISSUE TITLE
Workspace slug missing in URL when opening stories

### ISSUE THREAD

**Issue by feritarou** [Daniel-Griffiths/vscode-clubhouse#339]
When I attempt to open up a story in the browser, the workspace slug is missing in the URL. I don't know if it was intended that this be inferred from the API token - if yes, then this is just a bug; if no, I would suggest adding a new setting "Workspace slug" for this and similar interactions.

**Comment by Daniel-Griffiths** [comment]
I recently started using shortcut again and found myself needing this feature. I've finally added it in, thanks for the suggestion!
