### ISSUE TITLE
When Creating New Stories, Remove the Requirement to Set Projects (As They Are Now Deprecated)

### ISSUE THREAD

**Issue by feritarou** [Daniel-Griffiths/vscode-clubhouse#340]

**Comment by Daniel-Griffiths** [comment]
Hey @feritarou! 

Apologies I've only just seen the issues raised on this repo. 

I no longer use Shortcut or maintain this extension but if you would like to make a pull request to add/change any features I'd happily merge them in. 😄

**Comment by feritarou** [comment]
Hi Daniel,
Got it, thanks for getting back!

Daniel Griffiths ***@***.***> schrieb am Sa., 11. Mai 2024,
01:17:

**Comment by Daniel-Griffiths** [comment]
It's been a while but I finally got around to removing projects, thanks for the suggestion!
