### ISSUE TITLE
Commands do not work on Linux

### ISSUE THREAD

**Issue by LeonAlvarez** [Daniel-Griffiths/vscode-clubhouse#52]
I'm getting the following error:
![image](https://user-images.githubusercontent.com/22636643/69244822-f7048780-0ba5-11ea-9d8f-ecac995b7c8d.png)

Set username return similar error

**Comment by Daniel-Griffiths** [comment]
@LeonAlvarez sorry for the late reply, just to check which OS are you using (Mac Catalina, Ubuntu, Manjaro etc)? 

I have a Ubuntu machine and recall having a similar issue, a temporary solution was to build from source on that machine instead of downloading from the VSCode store.

**Comment by LeonAlvarez** [comment]
UbuntuEl 2 dic. 2019 10:05, Daniel Griffiths <notifications@github.com> escribió:Sorry @LeonAlvarez sorry for the late reply, just to check which OS are you using (Mac Catalina, Ubuntu, Manjaro etc)?

**Comment by Daniel-Griffiths** [comment]
Thanks @LeonAlvarez that confirms it's the same issue I had

A temporary solution is to clone the repo, run `yarn install && yarn build`. That should create a new VSIX file, this use the following guide to install it manually:

https://stackoverflow.com/questions/42017617/how-to-install-vs-code-extension-manually

I will get around to fixing this eventually, I have just been a bit busy recently :sweat_smile:

**Comment by Daniel-Griffiths** [comment]
@LeonAlvarez This issue should now be resolved. I am super late to fixing this but it's finally done. :slightly_smiling_face: 

v0.10.0 is now on the marketplace
