### ISSUE TITLE
Not found when trying to get stories

### ISSUE THREAD

**Issue by rdewolff** [Daniel-Griffiths/vscode-clubhouse#95]
On macOS, after setting up the token, when I try to get the stories, I get "Not found" error.

**Comment by richardhealy** [comment]
Same as above but with Windows using VM Linux. Also happens when trying to Search Stories.

**Comment by Daniel-Griffiths** [comment]
@rdewolff  @richardhealy 

This issue should now be resolved. I am super late to fixing this but it's finally done. :slightly_smiling_face: 

v0.10.0 is now on the marketplace

**Comment by richardhealy** [comment]
Can confirm this works now 👍
